name: stars

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: '30 3 * * *'
  workflow_dispatch:

jobs:
  stars:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: install dependencies
        run: pip install -r requirements.txt
      - name: generate stars.md
        env:
          GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
        run: python3 github_stars.py -v --json wlamason
      - name: git push
        run: |
          git config --global user.name "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.email "github-actions[bot]"
          git remote set-url origin https://x-access-token:${{ secrets.GIT_TOKEN }}@github.com/${{ github.repository }}
          git add stars.md
          git commit -m "$(date +%F) stars workflow run"
          git push
